import json
import webbrowser
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path

from cloudmesh.ai.command.git import UserConfig, fetch_all_repos_for_user


class GitViewServerHandler(BaseHTTPRequestHandler):
    """
    HTTP Handler to support Refresh and Delete operations for the Git Info View.
    """

    def do_GET(self):
        if self.path == "/":
            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            # The HTML is generated by GitInfoView and passed to the server
            self.wfile.write(self.server.view_instance.generate_html().encode("utf-8"))
        else:
            self.send_error(404)

    def do_POST(self):
        content_length = int(self.headers["Content-Length"])
        post_data = json.loads(self.rfile.read(content_length))

        if self.path == "/refresh":
            self.handle_refresh(post_data)
        elif self.path == "/delete":
            self.handle_delete(post_data)
        else:
            self.send_error(404)

    def handle_refresh(self, data):
        config = UserConfig()
        target_user = data.get("user")
        target_repo = data.get("repo")
        
        users = config.get_users() if not target_user else [target_user]
        all_fetched_repos = []
        missing_repos = []

        for user in users:
            # Force refresh from GitHub
            repos = fetch_all_repos_for_user(user, force=True, config=config)
            all_fetched_repos.extend(repos)
            
            # Check for missing repos in cache
            cached_repos = config.get_cached_repos(user) or []
            cached_names = {r["repo"] for r in cached_repos if isinstance(r, dict)}
            fetched_names = {r["repo"] for r in repos}
            
            for name in cached_names:
                if name not in fetched_names:
                    missing_repos.append({"user": user, "repo": name})

        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps({
            "status": "success",
            "missing": missing_repos
        }).encode("utf-8"))

    def handle_delete(self, data):
        user = data.get("user")
        repo_name = data.get("repo")
        if not user or not repo_name:
            self.send_error(400, "Missing user or repo")
            return

        config = UserConfig()
        repos = config.get_cached_repos(user) or []
        updated_repos = [r for r in repos if r.get("repo") != repo_name]
        
        if len(updated_repos) != len(repos):
            config.save_cached_repos(user, updated_repos)
            response = {"status": "deleted"}
        else:
            response = {"status": "not_found"}

        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(response).encode("utf-8"))


class GitInfoView:
    """
    Handles the generation and display of the HTML view for Git repository statistics using Tabulator.
    """

    def __init__(self, all_user_data, excludes=None, backup_dir=None):
        self.all_user_data = all_user_data
        self.excludes = excludes or []
        self.backup_dir = Path(backup_dir) if backup_dir else None

    def generate_html(self):
        """
        Generates a standalone HTML page for viewing repository statistics.
        """
        # Flatten data for Tabulator: {user: [repos]} -> [ {user: ..., ...repo_data}, ... ]
        flattened_data = []
        for user, repos in self.all_user_data.items():
            for repo in repos:
                repo_copy = repo.copy()
                # Enrich with download status
                is_downloaded = False
                if self.backup_dir:
                    repo_name = repo.get("repo", "").split("/")[-1]
                    repo_path = self.backup_dir / user / repo_name
                    if repo_path.exists() and repo_path.is_dir():
                        is_downloaded = True
                
                repo_copy["user"] = user
                repo_copy["downloaded"] = is_downloaded
                flattened_data.append(repo_copy)

        data_json = json.dumps(flattened_data)
        excludes_str = ', '.join(self.excludes) if self.excludes else ''

        # Read HTML template from file
        template_path = Path(__file__).parent / "git_view.html"
        try:
            with open(template_path, "r", encoding="utf-8") as f:
                html = f.read()
            
            # Replace placeholders
            html = html.replace("{{DATA_JSON}}", data_json)
            html = html.replace("{{EXCLUDES_STR}}", excludes_str)
            return html
        except Exception as e:
            return f"<h1 style='font-family: sans-serif;'>Error loading template</h1><p>{e}</p>"

    def open_in_browser(self):
        """
        Starts a local server and opens the Git Info View in the browser.
        """
        port = 8080
        try:
            server = HTTPServer(("localhost", port), GitViewServerHandler)
            server.view_instance = self
            
            webbrowser.open(f"http://localhost:{port}")
            print(f"\nServer running at http://localhost:{port}")
            print("Press Ctrl+C to stop the server and close the view.")
            
            server.serve_forever()
        except OSError as e:
            if e.errno == 98 or e.errno == 48: # Address already in use
                print(f"\nError: Port {port} is already in use. Please close other instances of the view.")
            else:
                print(f"\nError starting server: {e}")